In [1]:
import numpy as np 


In [2]:
my_list = [1,2,3] 
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3], [4,5,6]]
my_matrix

[[1, 2, 3], [4, 5, 6]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(2)

array([0.95568422, 0.66511012])

In [19]:
np.random.rand(5,5)

array([[0.14506098, 0.87716381, 0.98250303, 0.08083185, 0.50883758],
       [0.45040955, 0.94658856, 0.13936225, 0.19354901, 0.50285314],
       [0.13736976, 0.39678492, 0.85785387, 0.14091402, 0.13614512],
       [0.33014911, 0.30839696, 0.08187158, 0.2929891 , 0.34303361],
       [0.89018738, 0.24998489, 0.12230143, 0.11093682, 0.03299793]])

In [21]:
np.random.randn(4)

array([ 0.18690684, -0.35628972, -0.6161083 ,  0.23700798])

In [24]:
np.random.randint(1,100, 10)

array([54, 64, 23,  5, 85, 85, 74, 23, 92, 77], dtype=int32)

In [25]:
arr = np.arange(25)

In [26]:
ranarr = np.random.randint(0, 50, 10)

In [27]:
ranarr

array([12, 35, 36, 25, 39, 38,  6, 25, 37, 22], dtype=int32)

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr

array([12, 35, 36, 25, 39, 38,  6, 25, 37, 22], dtype=int32)

In [30]:
ranarr.max()

np.int32(39)

In [31]:
ranarr.argmax()

np.int64(4)

In [32]:
ranarr.min()

np.int32(6)

In [33]:
ranarr.argmin()

np.int64(6)

In [34]:
arr.shape

(25,)

In [35]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [36]:
arr.reshape(1,25).shape

(1, 25)

In [37]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [38]:
new_arr = np.arange(0, 11)

In [39]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
new_arr[8]

np.int64(8)

In [41]:
new_arr[1:5]

array([1, 2, 3, 4])

In [42]:
new_arr[0:5] = 100

In [43]:
new_arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [44]:
new_arr = np.arange(0, 11)

In [45]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
slice_of_arr = new_arr[0:6]

In [47]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [49]:
slice_of_arr [:] = 99

In [50]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [51]:
new_arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [52]:
arr_copy = new_arr.copy()

In [53]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr_2d = np.array(([5,10,15], [20, 25, 30], [35, 40, 45]))

In [56]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [57]:
arr_2d[1]

array([20, 25, 30])

In [58]:
arr_2d[2]

array([35, 40, 45])

In [59]:
arr_2d[0]

array([ 5, 10, 15])

In [60]:
arr_2d[0][1]

np.int64(10)

In [61]:
arr_2d[2][2]

np.int64(45)

In [62]:
arr_2d[2, 1]

np.int64(40)

In [65]:
arr_2d[:3, 1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [66]:
arr_2d[2, :]

array([35, 40, 45])

In [67]:
arr2 = np.zeros((10, 10))

In [68]:
arr2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
arr_length = arr2.shape[1]

In [70]:
arr_length

10

In [72]:
for i in range(arr_length):
    arr2[i] = i
arr2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [73]:
arr2[[2, 4, 6, 8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])